### ISSUE TITLE
Please merge the PR

### ISSUE THREAD

**Issue by danieluniform** [ArturMoczulski/rollbar-php-magento2#11]
The PR needs to be merged for compatibility with Magento >2.3.5 and 2.4.x 

Otherwise generates errors as there is no successful return. We had to make a patch when this should be updated to reflect the changes needed.

**Comment by danielmorell** [comment]
I am not sure which PR you are referring to, but both have been merged. I am sorry this took so long!

**Comment by danielmorell** [comment]
Both PRs were released in `v1.0.1`.
