### ISSUE TITLE
Not able to install rollbar-php-magento2 

### ISSUE THREAD

**Issue by wahidalipsq** [ArturMoczulski/rollbar-php-magento2#4]
Hi,
I am trying to integrate Rollbar magento sdk in my application but getting the following error.
```
Problem 1
   - The requested package rollbar-magento2 could not be found in any version, there may be a typo in the package name.
```
Below the steps which i have followed as per official document https://docs.rollbar.com/docs/magento-2
1.  Ran the following script
```
php bin/magento setup:upgrade
```
2. Added the following dependency in the composer.json
```
 "rollbar-magento2":"1.0.0"
```
3.  Ran the following script.
```
 composer update
```
Here is the output detail 
```
D:\xampp\htdocs\magento>composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

 Problem 1
   - The requested package rollbar-magento2 could not be found in any version, there may be a typo in the package name.

Potential causes:
- A typo in the package name
- The package is not available in a stable-enough version according to your minimum-stability setting
  see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.
- It's a private package and you forgot to add a custom repository to find it

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.
```
Please help me out .

Thanks,
Wahid

**Comment by im-jc** [comment]
Hi!
Please follow these steps to install rollbar.

1. Do install the extension through composer. Add rollbar/rollbar-magento2: * to your composer.json.
2.     Run composer update so composer regenerates your autloading files.
3.     Add access token.
4.     Test the result.


Thanks
